// Module include
#include "module.h"

// SNIPPET_START GLOBAL_INCLUDES
// Test include
#include "test.h"
// SNIPPET_END

// -------------------- DESCRIPTION START --------------------
// SNIPPET_START DESCRIPTION
// SNIPPET_END
// -------------------- DESCRIPTION END --------------------

// SNIPPET_START MODULE_INCLUDES
// SNIPPET_END

// SNIPPET_START MODULE_GLOBAL_VARIABLES
priorityqueueRECORD REC_PRIORITYQUEUE;

priorityqueueENTRY ENT_ENTRYC1 = { 10, 1, null, null, null };
priorityqueueENTRY ENT_ENTRYR1 = { 5, 2, null, null, null };
priorityqueueENTRY ENT_ENTRYL1 = { 15, 3, null, null, null };
priorityqueueENTRY ENT_ENTRYRR1 = { 3, 4, null, null, null };
priorityqueueENTRY ENT_ENTRYRL1 = { 7, 5, null, null, null };
priorityqueueENTRY ENT_ENTRYLR1 = { 13, 6, null, null, null };
priorityqueueENTRY ENT_ENTRYLL1 = { 17, 7, null, null, null };

priorityqueueENTRY ENT_ENTRYC2 = { 10, 10, null, null, null };
priorityqueueENTRY ENT_ENTRYR2 = { 5, 20, null, null, null };
priorityqueueENTRY ENT_ENTRYL2 = { 15, 30, null, null, null };
priorityqueueENTRY ENT_ENTRYRR2 = { 3, 40, null, null, null };
priorityqueueENTRY ENT_ENTRYRL2 = { 7, 50, null, null, null };
priorityqueueENTRY ENT_ENTRYLR2 = { 13, 60, null, null, null };
priorityqueueENTRY ENT_ENTRYLL2 = { 17, 70, null, null, null };

priorityqueueENTRY ENT_ENTRYC3 = { 10, 100, null, null, null };
priorityqueueENTRY ENT_ENTRYR3 = { 5, 200, null, null, null };
priorityqueueENTRY ENT_ENTRYL3 = { 15, 300, null, null, null };
priorityqueueENTRY ENT_ENTRYRR3 = { 3, 400, null, null, null };
priorityqueueENTRY ENT_ENTRYRL3 = { 7, 500, null, null, null };
priorityqueueENTRY ENT_ENTRYLR3 = { 13, 600, null, null, null };
priorityqueueENTRY ENT_ENTRYLL3 = { 17, 700, null, null, null };

priorityqueueENTRY ENT_ENTRYZERO1 = { 0, 8, null, null, null };
priorityqueueENTRY ENT_ENTRYZERO2 = { 0, 80, null, null, null };
priorityqueueENTRY ENT_ENTRYZERO3 = { 0, 800, null, null, null };
// SNIPPET_END

// SNIPPET_START MODULE_FUNCTIONS
// SNIPPET_END

// Module default partition
void MODULE_DEFAULTPARTITION(void) {
	// SNIPPET_START MODULE_DEFAULTPARTITION_VARIABLES
	// SNIPPET_END

	PRIORITYQUEUE_STARTUP(&REC_PRIORITYQUEUE, true, true);

	if (!PRIORITYQUEUE_ISEMPTY(&REC_PRIORITYQUEUE)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYC1);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYL1);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYR1);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYLL1);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYLR1);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYRL1);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYRR1);

	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYC2);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYL2);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYR2);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYLL2);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYLR2);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYRL2);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYRR2);

	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYC3);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYL3);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYR3);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYLL3);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYLR3);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYRL3);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYRR3);

	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYZERO1);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYZERO2);
	PRIORITYQUEUE_INITIALIZEENTRY(&ENT_ENTRYZERO3);

	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYC1);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYL1);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYR1);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYLL1);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYLR1);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYRL1);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYRR1);

	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYC2);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYL2);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYR2);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYLL2);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYLR2);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYRL2);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYRR2);

	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYC3);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYL3);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYR3);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYLL3);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYLR3);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYRL3);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYRR3);

	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYZERO1);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYZERO2);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYZERO3);

	if (PRIORITYQUEUE_ISEMPTY(&REC_PRIORITYQUEUE)) {
		while (true) {
		}
	}

	if (PRIORITYQUEUE_GETCOUNT(&REC_PRIORITYQUEUE) != 24) {
		while (true) {
		}
	}

	if (ENT_ENTRYC1.PRI_PRIORITY == 10) {
		ENT_ENTRYC1.PRI_PRIORITY = 11;
		if (ENT_ENTRYC1.PRI_PRIORITY == 11) {
			ENT_ENTRYC1.PRI_PRIORITY = 10;
		} else {
			while (true) {
			}
		}
	} else {
		while (true) {
		}
	}

	if (ENT_ENTRYC1.VAL_VALUE == 1) {
		ENT_ENTRYC1.VAL_VALUE = 2;
		if (ENT_ENTRYC1.VAL_VALUE == 2) {
			ENT_ENTRYC1.VAL_VALUE = 1;
		} else {
			while (true) {
			}
		}
	} else {
		while (true) {
		}
	}

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 0) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 8)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 0) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 80)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 0) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 800)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 3) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 4)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 3) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 40)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 3) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 400)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 5) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 2)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 5) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 20)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 5) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 200)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 7) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 5)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 7) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 50)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 7) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 500)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 10) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 1)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 10) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 10)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 10) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 100)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 13) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 6)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 13) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 60)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 13) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 600)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 15) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 3)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 15) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 30)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 15) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 300)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 17) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 7)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 17) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 70)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 17) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 700)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if (REC_PRIORITYQUEUE.ENT_HEAD != null) {
		while (true) {
		}
	}

	if (!PRIORITYQUEUE_ISEMPTY(&REC_PRIORITYQUEUE)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if (REC_PRIORITYQUEUE.ENT_HEAD != null) {
		while (true) {
		}
	}

	if (!PRIORITYQUEUE_ISEMPTY(&REC_PRIORITYQUEUE)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYC1);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYL1);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYR1);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYLL1);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYLR1);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYRL1);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYRR1);

	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYC2);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYL2);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYR2);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYLL2);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYLR2);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYRL2);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYRR2);

	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYC3);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYL3);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYR3);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYLL3);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYLR3);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYRL3);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYRR3);

	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYZERO1);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYZERO2);
	PRIORITYQUEUE_ENQUEUE(&REC_PRIORITYQUEUE, &ENT_ENTRYZERO3);

	if (PRIORITYQUEUE_ISEMPTY(&REC_PRIORITYQUEUE)) {
		while (true) {
		}
	}

	if (PRIORITYQUEUE_GETCOUNT(&REC_PRIORITYQUEUE) != 24) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(&ENT_ENTRYC1);
	PRIORITYQUEUE_REMOVE(&ENT_ENTRYL1);
	PRIORITYQUEUE_REMOVE(&ENT_ENTRYR1);
	PRIORITYQUEUE_REMOVE(&ENT_ENTRYLL1);
	PRIORITYQUEUE_REMOVE(&ENT_ENTRYLR1);
	PRIORITYQUEUE_REMOVE(&ENT_ENTRYRL1);
	PRIORITYQUEUE_REMOVE(&ENT_ENTRYRR1);

	PRIORITYQUEUE_REMOVE(&ENT_ENTRYC3);
	PRIORITYQUEUE_REMOVE(&ENT_ENTRYL3);
	PRIORITYQUEUE_REMOVE(&ENT_ENTRYR3);
	PRIORITYQUEUE_REMOVE(&ENT_ENTRYLL3);
	PRIORITYQUEUE_REMOVE(&ENT_ENTRYLR3);
	PRIORITYQUEUE_REMOVE(&ENT_ENTRYRL3);
	PRIORITYQUEUE_REMOVE(&ENT_ENTRYRR3);

	if (PRIORITYQUEUE_ISEMPTY(&REC_PRIORITYQUEUE)) {
		while (true) {
		}
	}

	if (PRIORITYQUEUE_GETCOUNT(&REC_PRIORITYQUEUE) != 10) {
		while (true) {
		}
	}

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 0) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 8)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 0) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 80)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 0) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 800)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 3) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 40)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 5) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 20)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 7) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 50)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 10) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 10)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 13) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 60)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 15) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 30)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if ((REC_PRIORITYQUEUE.ENT_HEAD->PRI_PRIORITY != 17) || (REC_PRIORITYQUEUE.ENT_HEAD->VAL_VALUE != 70)) {
		while (true) {
		}
	}

	PRIORITYQUEUE_REMOVE(REC_PRIORITYQUEUE.ENT_HEAD);

	if (REC_PRIORITYQUEUE.ENT_HEAD != null) {
		while (true) {
		}
	}

	if (!PRIORITYQUEUE_ISEMPTY(&REC_PRIORITYQUEUE)) {
		while (true) {
		}
	}

	while (true) {
	}
}
